---
- name: "Add Node.js from NodeSource"
  become: true
  shell : |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: "install Node.js 14"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cashe: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes